Helm (`helm`) extension support
zed-industries/extensions pull request #130
Opened 2024-02-26 04:04 UTC by hjoshi123

I'm fairly new to language configuration, lsp and tree sitter and was working on Helm charts so decided to create an extension for go templates.

Kindly let me know if something is missing.

2024-02-26 04:05 UTC, hjoshi123 commented
@cla-bot check

2024-02-26 16:48 UTC, hjoshi123 commented
@maxdeviant should the repo name for grammar be tree-sitter-helm? because its not that

2024-02-26 16:54 UTC, maxdeviant commented
> @maxdeviant should the repo name for grammar be tree-sitter-helm? because its not that

Hmm, I'm not 100% sure how the name of the resulting Wasm grammar is determined.

@maxbrunsfeld Do you know?

2024-03-04 07:55 UTC, hjoshi123 commented
@maxbrunsfeld how should I handle this? Should I change the name of the extension and folders so that it matches the repository of tree sitter?

2024-03-25 16:45 UTC, maxbrunsfeld requested changes

2024-03-25 16:45 UTC, maxbrunsfeld commented on .gitmodules
> +	url = https://github.com/hjoshi123/helm.zed.git
Would you mind naming the submodule folder `helm`? Also, in your extension, let's call the language `Helm` instead of `go-template`. Though it uses `go-template` for the grammar, the fact that YAML is injected seems to be Helm-specific (not just general Go template support).

2024-03-25 16:45 UTC, maxbrunsfeld commented on .gitmodules
> +	url = git@github.com:Brunowilliang/zedspace.git
Can you revert this submodule URL change? We need to use https for all submodules for our CI.

2024-03-25 16:45 UTC, maxbrunsfeld commented on extensions.toml
> +[go-template]
Let's call this `helm`.

2024-04-02 14:52 UTC, maxdeviant commented
> @hjoshi123 please do the needful

@cabrinha Please stop spamming this PR with messages like this. At this point we're aware of your desire for this extension.

Comments like this are just noise and are not doing anything in terms of making this work proceed any faster. If you would like to see this work proceed faster, consider helping out with the necessary changes.

2024-05-16 21:55 UTC, maxdeviant commented
Closing due to inactivity.

2024-05-16 21:55 UTC, closed without merging