Add support for OMNeT++ NED and MSG files
zed-industries/extensions pull request #1342
Opened 2024-09-02 13:07 UTC by adamgeorge309

NED and MSG (extensions .ned and .msg) are DSLs for the OMNeT++ network simulator. They are used by model frameworks for OMNeT++, such as the INET framework, Simu5G, Veins, etc. We are the team that develops [OMNeT++](https://github.com/omnetpp/omnetpp) and the [INET Framework](https://github.com/inet-framework/) and we have created tree-sitter grammars for these languages, as well as an extension for the Zed editor.

2024-09-03 12:18 UTC, adamgeorge309 commented
@cla-bot check

2024-09-09 15:39 UTC, maxdeviant requested changes
Could you please add the submodule to this PR?

The `.gitmodules` entry is present, but the submodule itself is not.

2024-09-09 15:40 UTC, maxdeviant commented on extensions.toml
> +path = "extensions/omnetpp"
We don't need this `path` here, as the extension repo has the extension at the root.

```suggestion
```

2024-09-10 11:57 UTC, adamgeorge309 commented
I added the submodule and accepted your change. Thanks!

2024-09-10 15:38 UTC, maxdeviant commented on extensions/omnetpp-zed
Can we change this directory to be just `extensions/omnetpp`, so it matches the extension ID?

2024-09-10 15:38 UTC, maxdeviant commented
It looks like there may be some conflicts with `main` that need to be resolved.

2024-09-10 16:23 UTC, adamgeorge309 commented on extensions/omnetpp-zed
Yes, we meant to do that, so that we don't have zed in the name.

2024-09-10 16:36 UTC, adamgeorge309 commented on extensions/omnetpp-zed
Do I understand correctly that `path = extensions/omnetpp` in .gitmodules specifies the directory name?

2024-09-10 20:45 UTC, maxdeviant commented on extensions/omnetpp-zed
`path` is for a path within the extension repository. It's generally not needed unless you have multiple extensions in a repository, or need them located someone other than the root.

But what we want is for the directory in this repository to be `extensions/omnetpp`. The actual repository name can be `omnetpp-zed`.

What you want to do is add the submodule like this:

```sh
git submodule add https://github.com/omnetpp/omnetpp-zed.git extensions/omnetpp
```

2024-09-11 13:37 UTC, adamgeorge309 commented on extensions/omnetpp-zed
I did this, thank you!

2024-09-25 09:21 UTC, adamgeorge309 commented
I fixed the extension ID in extension.toml to match extensions.toml

2024-10-02 14:02 UTC, maxdeviant commented
> @maxdeviant, I fixed the extension ID in extension.toml to match extensions.toml

@adamgeorge309 I see the correct ID in your extension repository, but the submodule commit in this repo needs to be updated to match. I don't have the ability to push any changes to this branch, as your fork is on a GitHub organization.

2024-10-04 14:03 UTC, merged

2024-10-04 14:57 UTC, adamgeorge309 commented
Thank you