Add ziggy
zed-industries/extensions pull request #1735
Opened 2024-12-01 13:03 UTC by lvignoli

[Ziggy](https://ziggy-lang.io) support for Zed.

The LSP cannot be installed because of an upstream issue: releases for ziggy are distributed as `tar.xz`, not `tar.gz`.
As I understand, Zed extension SDK does not support this compression format.

2024-12-02 18:03 UTC, notpeter commented
If we know that the download/extraction will fail, can we comment out that code and just require users to manually download and install ziggy into their PATH and output an error if `which` doesn't find the ziggy binary?

2024-12-02 18:04 UTC, notpeter requested changes
If we know that the download/extraction will fail, can we:
1. comment out that code
2. require users to manually download and install `ziggy` into their PATH 
3. output an error when `which` fails to find the ziggy binary?

2024-12-03 20:53 UTC, lvignoli commented
@notpeter indeed, that's much sounder. Is this the proper way to do so?

2024-12-03 23:45 UTC, notpeter approved these changes

2024-12-03 23:45 UTC, merged

2024-12-03 23:45 UTC, notpeter commented
Thanks!