Add zed-asciidoc 0.0.1
zed-industries/extensions pull request #419
Opened 2024-03-30 11:46 UTC by andreicek

This adds support for AsciiDoc syntax highlighting.

The tree sitter is still WIP, but it works to some extent and it's good to see at least a bit of color in the editor.

2024-03-30 11:47 UTC, andreicek commented
@cla-bot check

2024-04-01 14:39 UTC, maxdeviant requested changes
Thanks for creating this, @andreicek!

Could we drop the `-zed` suffix from the extension ID? https://github.com/andreicek/zed-asciidoc/blob/b940fc1dff376f6eae860c577b4b0435a5bf9fb7/extension.toml#L1

Since these are all Zed extensions we don't need to clarify.

2024-04-21 08:20 UTC, andreicek commented
@maxdeviant sorry for keeping this PR waiting. I updated the name, can you please check everything is in order now?

2024-04-22 10:12 UTC, huacnlee commented on .gitmodules
> +[submodule "extensions/zed-asciidoc"]
Maybe you also need to remove the `zed-` prefix for submodule path.

2024-04-22 15:11 UTC, maxdeviant approved these changes
Thanks for this, @andreicek!

2024-04-22 15:12 UTC, merged