Add Glazier themes
zed-industries/extensions pull request #448
Opened 2024-04-06 11:26 UTC by airgap

1. Glazier | Phantom
2. Glazier | Deep Space
3. Glazier | Redrum

Early prototype

2024-04-06 11:42 UTC, airgap commented
@cla-bot check

2024-04-07 11:59 UTC, maxdeviant requested changes
Would you mind adjusting the version number so it doesn't have all zero components?

It looks like the Git submodule is missing as well (we have a `.gitmodules` entry, but no actual submodule committed).

2024-04-07 11:59 UTC, maxdeviant commented on extensions.toml
> +version = "0.0.0"
Could we use a non-zero version here?

2024-04-09 12:40 UTC, maxdeviant approved these changes
@airgap Thank you!

2024-04-09 12:41 UTC, merged